# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogom/proto/PogomResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogom/proto/PogomResponse.proto',
  package='',
  serialized_pb=_b('\n\x1fpogom/proto/PogomResponse.proto\"r\n\x08Response\x12\x12\n\x04gyms\x18\x01 \x03(\x0b\x32\x04.Gym\x12\x19\n\x07pokemon\x18\x02 \x03(\x0b\x32\x08.Pokemon\x12\x1c\n\tpokestops\x18\x03 \x03(\x0b\x32\t.Pokestop\x12\x19\n\x07scanned\x18\x04 \x03(\x0b\x32\x08.Scanned\"2\n\x0b\x43oordinates\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\x9f\x01\n\x03Gym\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x18\n\x10guard_pokemon_id\x18\x02 \x01(\x05\x12\x0e\n\x06gym_id\x18\x03 \x01(\t\x12\x12\n\ngym_points\x18\x04 \x01(\x03\x12\x15\n\rlast_modified\x18\x05 \x01(\x03\x12!\n\x0b\x63oordinates\x18\x06 \x01(\x0b\x32\x0c.Coordinates\x12\x0f\n\x07team_id\x18\x07 \x01(\x05\"\t\n\x07Pokemon\"\n\n\x08Pokestop\"\t\n\x07Scanned')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyms', full_name='Response.gyms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon', full_name='Response.pokemon', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokestops', full_name='Response.pokestops', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scanned', full_name='Response.scanned', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=149,
)


_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Coordinates.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Coordinates.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=201,
)


_GYM = _descriptor.Descriptor(
  name='Gym',
  full_name='Gym',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='Gym.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guard_pokemon_id', full_name='Gym.guard_pokemon_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gym_id', full_name='Gym.gym_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gym_points', full_name='Gym.gym_points', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_modified', full_name='Gym.last_modified', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='Gym.coordinates', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='team_id', full_name='Gym.team_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=363,
)


_POKEMON = _descriptor.Descriptor(
  name='Pokemon',
  full_name='Pokemon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=374,
)


_POKESTOP = _descriptor.Descriptor(
  name='Pokestop',
  full_name='Pokestop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=386,
)


_SCANNED = _descriptor.Descriptor(
  name='Scanned',
  full_name='Scanned',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=397,
)

_RESPONSE.fields_by_name['gyms'].message_type = _GYM
_RESPONSE.fields_by_name['pokemon'].message_type = _POKEMON
_RESPONSE.fields_by_name['pokestops'].message_type = _POKESTOP
_RESPONSE.fields_by_name['scanned'].message_type = _SCANNED
_GYM.fields_by_name['coordinates'].message_type = _COORDINATES
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.message_types_by_name['Gym'] = _GYM
DESCRIPTOR.message_types_by_name['Pokemon'] = _POKEMON
DESCRIPTOR.message_types_by_name['Pokestop'] = _POKESTOP
DESCRIPTOR.message_types_by_name['Scanned'] = _SCANNED

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'pogom.proto.PogomResponse_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATES,
  __module__ = 'pogom.proto.PogomResponse_pb2'
  # @@protoc_insertion_point(class_scope:Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)

Gym = _reflection.GeneratedProtocolMessageType('Gym', (_message.Message,), dict(
  DESCRIPTOR = _GYM,
  __module__ = 'pogom.proto.PogomResponse_pb2'
  # @@protoc_insertion_point(class_scope:Gym)
  ))
_sym_db.RegisterMessage(Gym)

Pokemon = _reflection.GeneratedProtocolMessageType('Pokemon', (_message.Message,), dict(
  DESCRIPTOR = _POKEMON,
  __module__ = 'pogom.proto.PogomResponse_pb2'
  # @@protoc_insertion_point(class_scope:Pokemon)
  ))
_sym_db.RegisterMessage(Pokemon)

Pokestop = _reflection.GeneratedProtocolMessageType('Pokestop', (_message.Message,), dict(
  DESCRIPTOR = _POKESTOP,
  __module__ = 'pogom.proto.PogomResponse_pb2'
  # @@protoc_insertion_point(class_scope:Pokestop)
  ))
_sym_db.RegisterMessage(Pokestop)

Scanned = _reflection.GeneratedProtocolMessageType('Scanned', (_message.Message,), dict(
  DESCRIPTOR = _SCANNED,
  __module__ = 'pogom.proto.PogomResponse_pb2'
  # @@protoc_insertion_point(class_scope:Scanned)
  ))
_sym_db.RegisterMessage(Scanned)


# @@protoc_insertion_point(module_scope)
